version: '3.8'

services:
  bot:
    build: .
    env_file:
      - .env
    depends_on:
      - db
      - init_db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
  init_db:
    build: .
    command: [ "python", "database_table_configuration.py" ]
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data: